@baseUrl=http://localhost:8002/v1/2025

# user register

POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "verify_key": "ttri0403@hotmail.com",
  "verify_purpose": "test",
  "verify_type": 1
}

