// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 0003_pre_go_acc_user_two_factor_9999.sql

package database

import (
	"context"
	"database/sql"
)

const addOrUpdateEmail = `-- name: AddOrUpdateEmail :exec
INSERT INTO pre_go_acc_user_two_factor_9999 (user_id, two_factor_email, two_factor_is_active)
VALUES (?, ?, TRUE)
ON DUPLICATE KEY UPDATE
    two_factor_email = VALUES(two_factor_email),
    two_factor_updated_at = NOW()
`

type AddOrUpdateEmailParams struct {
	UserID         int32
	TwoFactorEmail sql.NullString
}

func (q *Queries) AddOrUpdateEmail(ctx context.Context, arg AddOrUpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, addOrUpdateEmail, arg.UserID, arg.TwoFactorEmail)
	return err
}

const addOrUpdateTwoFactor = `-- name: AddOrUpdateTwoFactor :exec
INSERT INTO pre_go_acc_user_two_factor_9999 (user_id, two_factor_phone, two_factor_is_active)
VALUES (?, ?, TRUE)
ON DUPLICATE KEY UPDATE
    two_factor_phone = VALUES(two_factor_phone),
    two_factor_updated_at = NOW()
`

type AddOrUpdateTwoFactorParams struct {
	UserID         int32
	TwoFactorPhone sql.NullString
}

func (q *Queries) AddOrUpdateTwoFactor(ctx context.Context, arg AddOrUpdateTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, addOrUpdateTwoFactor, arg.UserID, arg.TwoFactorPhone)
	return err
}

const countActiveTwoFactorMethods = `-- name: CountActiveTwoFactorMethods :one
SELECT COUNT(*)
FROM pre_go_acc_user_two_factor_9999
WHERE user_id = ? AND two_factor_is_active = 1
`

func (q *Queries) CountActiveTwoFactorMethods(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTwoFactorMethods, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disableTwoFactor = `-- name: DisableTwoFactor :exec
UPDATE pre_go_acc_user_two_factor_9999
SET two_factor_is_active = 0,
    two_factor_updated_at = NOW()
WHERE user_id = ? AND two_factor_auth_type = ?
`

type DisableTwoFactorParams struct {
	UserID            int32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
}

func (q *Queries) DisableTwoFactor(ctx context.Context, arg DisableTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, disableTwoFactor, arg.UserID, arg.TwoFactorAuthType)
	return err
}

const enableTwoFactorTypeEmail = `-- name: EnableTwoFactorTypeEmail :exec
INSERT INTO pre_go_acc_user_two_factor_9999 
  (user_id, two_factor_auth_type, two_factor_email, two_factor_auth_secret, two_factor_is_active, two_factor_created_at, two_factor_updated_at)
VALUES (?, ?, ?, "OTP", FALSE, NOW(), NOW())
`

type EnableTwoFactorTypeEmailParams struct {
	UserID            int32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
	TwoFactorEmail    sql.NullString
}

func (q *Queries) EnableTwoFactorTypeEmail(ctx context.Context, arg EnableTwoFactorTypeEmailParams) error {
	_, err := q.db.ExecContext(ctx, enableTwoFactorTypeEmail, arg.UserID, arg.TwoFactorAuthType, arg.TwoFactorEmail)
	return err
}

const enableTwoFactorTypeSMS = `-- name: EnableTwoFactorTypeSMS :exec
INSERT INTO pre_go_acc_user_two_factor_9999 
  (user_id, two_factor_auth_type, two_factor_phone, two_factor_auth_secret, two_factor_is_active, two_factor_created_at, two_factor_updated_at)
VALUES (?, ?, ?, "OTP", FALSE, NOW(), NOW())
`

type EnableTwoFactorTypeSMSParams struct {
	UserID            int32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
	TwoFactorPhone    sql.NullString
}

func (q *Queries) EnableTwoFactorTypeSMS(ctx context.Context, arg EnableTwoFactorTypeSMSParams) error {
	_, err := q.db.ExecContext(ctx, enableTwoFactorTypeSMS, arg.UserID, arg.TwoFactorAuthType, arg.TwoFactorPhone)
	return err
}

const getTwoFactorMethodsByID = `-- name: GetTwoFactorMethodsByID :one
SELECT two_factor_id, user_id, two_factor_auth_type, two_factor_auth_secret,
       two_factor_phone, two_factor_email, two_factor_is_active,
       two_factor_created_at, two_factor_updated_at
FROM pre_go_acc_user_two_factor_9999
WHERE two_factor_id = ?
LIMIT 1
`

func (q *Queries) GetTwoFactorMethodsByID(ctx context.Context, twoFactorID uint32) (PreGoAccUserTwoFactor9999, error) {
	row := q.db.QueryRowContext(ctx, getTwoFactorMethodsByID, twoFactorID)
	var i PreGoAccUserTwoFactor9999
	err := row.Scan(
		&i.TwoFactorID,
		&i.UserID,
		&i.TwoFactorAuthType,
		&i.TwoFactorAuthSecret,
		&i.TwoFactorPhone,
		&i.TwoFactorEmail,
		&i.TwoFactorIsActive,
		&i.TwoFactorCreatedAt,
		&i.TwoFactorUpdatedAt,
	)
	return i, err
}

const getTwoFactorMethodsByIDAndType = `-- name: GetTwoFactorMethodsByIDAndType :one
SELECT two_factor_id, user_id, two_factor_auth_type, two_factor_auth_secret,
       two_factor_phone, two_factor_email, two_factor_is_active,
       two_factor_created_at, two_factor_updated_at
FROM pre_go_acc_user_two_factor_9999
WHERE two_factor_id = ? AND two_factor_auth_type = ?
LIMIT 1
`

type GetTwoFactorMethodsByIDAndTypeParams struct {
	TwoFactorID       uint32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
}

func (q *Queries) GetTwoFactorMethodsByIDAndType(ctx context.Context, arg GetTwoFactorMethodsByIDAndTypeParams) (PreGoAccUserTwoFactor9999, error) {
	row := q.db.QueryRowContext(ctx, getTwoFactorMethodsByIDAndType, arg.TwoFactorID, arg.TwoFactorAuthType)
	var i PreGoAccUserTwoFactor9999
	err := row.Scan(
		&i.TwoFactorID,
		&i.UserID,
		&i.TwoFactorAuthType,
		&i.TwoFactorAuthSecret,
		&i.TwoFactorPhone,
		&i.TwoFactorEmail,
		&i.TwoFactorIsActive,
		&i.TwoFactorCreatedAt,
		&i.TwoFactorUpdatedAt,
	)
	return i, err
}

const getTwoFactorStatus = `-- name: GetTwoFactorStatus :one
SELECT two_factor_is_active
FROM pre_go_acc_user_two_factor_9999
WHERE user_id = ? AND two_factor_auth_type = ?
LIMIT 1
`

type GetTwoFactorStatusParams struct {
	UserID            int32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
}

func (q *Queries) GetTwoFactorStatus(ctx context.Context, arg GetTwoFactorStatusParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, getTwoFactorStatus, arg.UserID, arg.TwoFactorAuthType)
	var two_factor_is_active bool
	err := row.Scan(&two_factor_is_active)
	return two_factor_is_active, err
}

const getUserFactorMethods = `-- name: GetUserFactorMethods :many
SELECT two_factor_id, user_id, two_factor_auth_type, two_factor_auth_secret,
       two_factor_phone, two_factor_email, two_factor_is_active,
       two_factor_created_at, two_factor_updated_at
FROM pre_go_acc_user_two_factor_9999
WHERE user_id = ?
`

func (q *Queries) GetUserFactorMethods(ctx context.Context, userID int32) ([]PreGoAccUserTwoFactor9999, error) {
	rows, err := q.db.QueryContext(ctx, getUserFactorMethods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreGoAccUserTwoFactor9999
	for rows.Next() {
		var i PreGoAccUserTwoFactor9999
		if err := rows.Scan(
			&i.TwoFactorID,
			&i.UserID,
			&i.TwoFactorAuthType,
			&i.TwoFactorAuthSecret,
			&i.TwoFactorPhone,
			&i.TwoFactorEmail,
			&i.TwoFactorIsActive,
			&i.TwoFactorCreatedAt,
			&i.TwoFactorUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTwoFactorEnabled = `-- name: IsTwoFactorEnabled :one
SELECT COUNT(*)
FROM pre_go_acc_user_two_factor_9999
WHERE user_id = ? AND two_factor_is_active = 1
`

func (q *Queries) IsTwoFactorEnabled(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, isTwoFactorEnabled, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const reactivateTwoFactor = `-- name: ReactivateTwoFactor :exec
UPDATE pre_go_acc_user_two_factor_9999
SET two_factor_is_active = 1, 
    two_factor_updated_at = NOW()
WHERE user_id = ? AND two_factor_auth_type = ?
`

type ReactivateTwoFactorParams struct {
	UserID            int32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
}

func (q *Queries) ReactivateTwoFactor(ctx context.Context, arg ReactivateTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, reactivateTwoFactor, arg.UserID, arg.TwoFactorAuthType)
	return err
}

const removeTwoFactor = `-- name: RemoveTwoFactor :exec
DELETE FROM pre_go_acc_user_two_factor_9999
WHERE user_id = ? AND two_factor_auth_type = ?
`

type RemoveTwoFactorParams struct {
	UserID            int32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
}

func (q *Queries) RemoveTwoFactor(ctx context.Context, arg RemoveTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, removeTwoFactor, arg.UserID, arg.TwoFactorAuthType)
	return err
}

const updateTwoFactorStatusVerification = `-- name: UpdateTwoFactorStatusVerification :exec
UPDATE pre_go_acc_user_two_factor_9999
SET two_factor_is_active = 1, 
    two_factor_updated_at = NOW()
WHERE user_id = ? AND two_factor_auth_type = ? AND two_factor_is_active = 0
`

type UpdateTwoFactorStatusVerificationParams struct {
	UserID            int32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
}

func (q *Queries) UpdateTwoFactorStatusVerification(ctx context.Context, arg UpdateTwoFactorStatusVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateTwoFactorStatusVerification, arg.UserID, arg.TwoFactorAuthType)
	return err
}

const verifyTwoFactor = `-- name: VerifyTwoFactor :one
SELECT COUNT(*)
FROM pre_go_acc_user_two_factor_9999
WHERE user_id = ? AND two_factor_auth_type = ? AND two_factor_is_active = 1
LIMIT 1
`

type VerifyTwoFactorParams struct {
	UserID            int32
	TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
}

func (q *Queries) VerifyTwoFactor(ctx context.Context, arg VerifyTwoFactorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, verifyTwoFactor, arg.UserID, arg.TwoFactorAuthType)
	var count int64
	err := row.Scan(&count)
	return count, err
}
