// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 0004_pre_go_ticket_item_999.sql

package database

import (
	"context"
)

const getTicketItemByID = `-- name: GetTicketItemByID :one



SELECT id, name, stock_initial ,stock_available
FROM pre_go_ticket_item_999 
WHERE id = ?
`

type GetTicketItemByIDRow struct {
	ID             int64
	Name           string
	StockInitial   int32
	StockAvailable int32
}

// file: pre_go_ticket_item_999.sql
func (q *Queries) GetTicketItemByID(ctx context.Context, id int64) (GetTicketItemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketItemByID, id)
	var i GetTicketItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StockInitial,
		&i.StockAvailable,
	)
	return i, err
}
