// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type PreGoAccUser9999 struct {
	// User ID
	UserID uint64
	// User account
	UserAccount string
	// User nickname
	UserNickname sql.NullString
	// User avatar
	UserAvatar sql.NullString
	// User state: 0-Locked ,  1-Activated ,  2-Not Activated
	UserState uint8
	// Mobile phone number
	UserMobile sql.NullString
	// User gender: 0-Secret ,  1-Male ,  2-Female
	UserGender sql.NullInt16
	// User birthday
	UserBirthday sql.NullTime
	// User email address
	UserEmail sql.NullString
	// Authentication status: 0-Not Authenticated ,  1-Pending ,  2-Authenticated ,  3-Failed
	UserIsAuthentication uint8
	// Record creation time
	CreatedAt sql.NullTime
	// Record update time
	UpdatedAt sql.NullTime
}

type PreGoAccUserBase9999 struct {
	UserID         int32
	UserAccount    string
	UserPassword   string
	UserSalt       string
	UserLoginTime  sql.NullTime
	UserLogoutTime sql.NullTime
	UserLoginIp    sql.NullString
	UserCreatedAt  sql.NullTime
	UserUpdatedAt  sql.NullTime
}

type PreGoAccUserVerify9999 struct {
	VerifyID        int32
	VerifyOtp       string
	VerifyKey       string
	VerifyKeyHash   string
	VerifyType      sql.NullInt32
	IsVerified      sql.NullInt32
	IsDeleted       sql.NullInt32
	VerifyCreatedAt sql.NullTime
	VerifyUpdatedAt sql.NullTime
}
