name: go-ecommerce-backend-api

services:
  mysql:
    image: mysql:8.0
    container_name: go-ecommerce-mysql
    # restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Cho phép mật khẩu trống cho root
      MYSQL_ROOT_PASSWORD: "1"
    ports:
      - "3306:3306"  # Ánh xạ cổng 3306
    volumes:
      - mysql-data:/var/lib/mysql
    
    networks:
      - go-ecommerce-network

  redis:
    image: redis:7.2
    container_name: go-ecommerce-redis
    # restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", ""]
    volumes:
      - redis_data:/data
    networks:
      - go-ecommerce-network

volumes:
  mysql-data:
    driver: local
  redis_data:
    driver: local

networks:
  go-ecommerce-network:
    driver: bridge
