package initialize

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go-ecommerce-backend-api.com/cmd/swag/docs"
	// "./docs" // Code generated by swaggo/swag.
)

// @title           API Documentation Ecommerce Backend
// @version         1.0.0
// @description     This is a sample server celler server.
// @termsOfService  github.com/thientrile/go-ecommerce-backend-api

// @contact.name  	Team TIPGO
// @contact.url    thientrile.github.io
// @contact.email  team@tipgo.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8002
// @BasePath  /v1/2025

// @securityDefinitions.basic  BasicAuth

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/

func InitSwagger(r *gin.Engine) *gin.Engine {

	docs.SwaggerInfo.Title = "API Documentation Ecommerce Backend"
	docs.SwaggerInfo.Description = "This is a sample server celler server."
	docs.SwaggerInfo.Version = "1.0.0"
	docs.SwaggerInfo.Host = "localhost:8002"
	docs.SwaggerInfo.BasePath = "/v1/2025"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}
	// use ginSwagger middleware to serve the API docs
	r.GET("/swagger//*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}
