global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Go E-commerce Backend API (running on host in dev mode)
  - job_name: 'go-ecommerce-api'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # # MySQL Exporter
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
  #   scrape_interval: 10s

  # Redis Exporter
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #   scrape_interval: 10s

  # Kafka Exporter
  # - job_name: 'kafka'
  #   static_configs:
  #     - targets: ['kafka-exporter:9308']
  #   scrape_interval: 10s

  # Node Exporter (System metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 10s

  # # Nginx metrics (if available)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx-dev:80', 'nginx-prod:80']
  #   metrics_path: '/nginx_status'
  #   scrape_interval: 10s
