server:
  port: 8082
databases:
- user: admin
  password: admin
  host: localhost
  dbName: shopDev
- user: order
  password: order
  host: localhost
  dbName: orderDev  
security:
  jwt:
    key: abcd1234
    algorithm: HS256
    expiration: 3600