server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 1
  dbname: shopDevgo
  maxIdleConns: 10 # Số kết nối nhàn rỗi tối đa
  maxOpenConns: 100 # Số kết nối mở tối đa
  connMaxLifetime: 3600 # Thời gian tối đa của kết nối (giây)
logger:
  log_level: debug # Mức độ log: debug, info, warn, error
  file_log_name: "./storage/logs/dev.xxx.log" # Tên file log
  max_size: 500
  max_backups: 3 # Số lượng bản sao lưu tối đa
  max_age: 30 # Số ngày lưu trữ log
  compress: true # Nén file log