server:
  port: 8002
  mode: dev # Chế độ chạy: dev, prod
mysql:
  host: 127.0.0.1
  port: 3306 #3306
  username: root
  password: strongpassword123!
  dbname: shopDevgo
  maxIdleConns: 10 # Số kết nối nhàn rỗi tối đa
  maxOpenConns: 100 # Số kết nối mở tối đa
  connMaxLifetime: 3600 # Thời gian tối đa của kết nối (giây)
  connMaxIdleTime: 300 # Thời gian tối đa của kết nối nhàn rỗi (giây)
logger:
  log_level: debug # Mức độ log: debug, info, warn, error
  file_log_name: "dev" # Tên file log
  file_log_path: "./storage/logs" # Thư mục lưu trữ log
  max_size: 500
  max_backups: 3 # Số lượng bản sao lưu tối đa
  max_age: 30 # Số ngày lưu trữ log
  compress: true # Nén file log
redis:
  host: 127.0.0.1 #go-ecommerce-redis
  port: 6379 #6379
  password: "strongredispass"
  database: 0
  pool_size: 10 # Kích thước pool kết nối Redis
kafka:
  host: localhost
  port: 29092
  topic:
    product: "product-topic"
    order: "order-topic"
    auth: "otp-auth-topic"    